// Explore dataset: CarbonBetter's real June 2026 catalogue for New Belgium (26 projects).
// Generated by extract/build_catalogue_js.py. PRICE BANDS ONLY - real quotes are
// in js/prices.local.js, which is gitignored and absent from the public deploy.
window.CATALOGUE = [
  {
    "key": "s27",
    "name": "Smart Thermostat Energy Efficiency Project",
    "registry": "Verra (VCS3352)",
    "vintage": "2021-2022",
    "creditType": "Avoidance",
    "category": "Energy demand",
    "tech": "Energy demand",
    "location": "All across USA",
    "country": "United States",
    "states": [],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "TÜV SÜD America Inc.",
    "quality": [
      "ICVCM CCP",
      "BeZero BBB"
    ],
    "volume": "50,000",
    "priceBand": "$5–10/t",
    "priceLow": 8.0,
    "description": "The project is implemented across residential homes throughout the United States, with groupings based on regional climate zones and equipment types. This project reduces greenhouse gas emissions by using smart thermostats with remote optimization software to lower energy consumption in residential heating and cooling systems. By intelligently managing electricity and natural gas use, the project delivers deep energy savings without requiring behavior changes from residents. Implemented across homes in the United States, it is expected to reduce over 3.8 million tonnes of CO₂ during the crediting period. The project uses a robust control group approach and separate regression models to account for differences in HVAC systems and ensure accurate baseline estimation. Emissions are calculated with EPA eGRID data and disaggregated by heating source. Co Benefits include: improved residential energy efficiency, reduced GHG emissions, enhanced indoor air quality, and support for green technology jobs in data science and engineering. The Project contributes to the following UN SDGs: SDG 7: Affordable and Clean Energy. Improves energy efficiency through advanced smart thermostat optimization. SDG 8: Decent Work and Economic Growth. Supports job creation and innovation in clean technology and software development. SDG 11: Sustainable Cities and Communities. Reduces urban air pollutants (e.g., PM2.5) by lowering fossil fuel consumption in homes. SDG 12: Responsible Consumption and Production. Encourages sustainable energy use and consumption in residential buildings."
  },
  {
    "key": "s18",
    "name": "Darkwoods Forest Carbon Project",
    "registry": "Verra (VCS607)",
    "vintage": "2021",
    "creditType": "Mixed",
    "category": "Forestry",
    "tech": "Agriculture Forestry",
    "location": "Canada",
    "country": "Canada",
    "states": [],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "Avoidance",
    "quality": [
      "BeZero bbb",
      "CCB Gold",
      "SD VISta"
    ],
    "volume": "150kt",
    "priceBand": "$15–20/t",
    "priceLow": 15.5,
    "description": "The Darkwood Forest Carbon Project is Canada’s longest standing project in VCM and protects over 55,000 hectares of forest in British Columbia from logging and development. It is the ONLY forestry-based project in North America with high ratings and both CCB Gold and SD Vista certification. It is managed by an NGO dedicated to sustainability. The project conserves critical ecosystems while avoiding significant greenhouse gas emissions. By maintaining intact forests, Darkwoods ensures long-term carbon storage and landscape resilience. It has very robust MRV process including baseline modeling of logging scenarios, physical inventory of forest data, and remote sensing to track forest cover over time. Beyond carbon, Darkwoods has certified co-benefits under both CCB Gold and SD Vista and delivers wide-ranging ecological and social benefits. The project protects habitat for threatened species like grizzly bears and mountain caribou, safeguards water quality, and enhances regional biodiversity. It also supports recreational access and educational opportunities, strengthening community and conservation values. It has been a great project for Canadians in BC Credits are a mix of removals and avoidance (~70-80% removal credits given the age of the project) as the VM0012 methodology under which it is registered does not allow their segregation for now. This is expected to change next year."
  },
  {
    "key": "s20",
    "name": "Durango Forest Project",
    "registry": "Climate Action Reserve (CAR1663)",
    "vintage": "2022 – 2023",
    "creditType": "Removal",
    "category": "Forestry",
    "tech": "IFM Removals",
    "location": "Mexico",
    "country": "Mexico",
    "states": [],
    "valueChainStates": [],
    "methodology": "CAR Mexico Forest Protocol V3.0",
    "verifier": "",
    "quality": [
      "ICVCM CCP",
      "Sylvera BBB"
    ],
    "volume": "50,000",
    "priceBand": "$15–20/t",
    "priceLow": 15.5,
    "description": "Located in Durango, Mexico, in Ejido Pueblo Nuevo within the municipality of Pueblo NuevoAn IFM project focused on improved forest management across a large community-owned forest landscape, combining enhanced silvicultural practices, natural regeneration, targeted reforestation, and restoration of degraded areas. Management is based on 100% native forest ecosystems, including pine, pine-oak, oak, oak-pine, and tropical dry forest types, with reforestation carried out using native plants produced in the ejido’s nursery. The project includes sustainable timber harvesting under an authorized long-term forest management program, alongside practices designed to improve stand productivity, regeneration, and carbon stocks over time. Supported by a strong management and monitoring framework covering silvicultural treatments, fire prevention and brigades, pest and disease surveillance, restoration works, and ongoing field controls. Delivers meaningful co-benefits, including community-based forest stewardship, rural livelihoods, biodiversity protection, watershed protection, erosion control, and long-term landscape resilience. Aligned with SDGs 5, 6, 8, 13, 15"
  },
  {
    "key": "s19",
    "name": "Kite Hammock IFM",
    "registry": "American Carbon Registry (ACR509)",
    "vintage": "2020, 2021",
    "creditType": "Mixed",
    "category": "Forestry",
    "tech": "Improved forest management (IFM)",
    "location": "Florida, US",
    "country": "United States",
    "states": [
      "FL"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "S&A Carbon",
    "quality": [
      "Sylvera BBB"
    ],
    "volume": "Removals – V21: 12,990 and V20: 13,025 Avoidance – V21 41,120 and V20: 41,000",
    "priceBand": "$5–25/t",
    "priceLow": 9.75,
    "description": "The Kite Hammock IFM project conserves 5,274 acres of mature Bottomland Hardwood Forest in Florida’s Nature Coast. By halting timber harvest, it protects watershed health, preserves biodiversity, and maintains nesting habitat for the Swallow-tailed. Monitoring of this project involved both physical on-ground measurements and remote sensing by using GIS data derived from GPS coordinates. Timber harvesting also is not allowed in this project. The Project contributes to the following UN SDGs: SDG 15: Life on Land. Conserves 5,274 acres of mature Bottomland Hardwood Forest, protecting biodiversity, preventing deforestation, and sustaining natural habitats. SDG 13: Climate Action. Avoids emissions from deforestation, enhances carbon storage, and supports climate resilience. SDG 6: Clean Water and Sanitation. Protects water-related ecosystems and maintains watershed health. SDG 3: Good Health and Well-Being. Improves air, water, and soil quality, reducing risks to human health."
  },
  {
    "key": "s21",
    "name": "Los Bancos Indigenous Community",
    "registry": "Climate Action Reserve (CAR1392)",
    "vintage": "2023",
    "creditType": "Removal",
    "category": "Forestry",
    "tech": "IFM Removals",
    "location": "Mexico",
    "country": "Mexico",
    "states": [],
    "valueChainStates": [],
    "methodology": "CAR Mexico Forest Protocol V3.0",
    "verifier": "",
    "quality": [
      "ICVCM CCP",
      "Sylvera A"
    ],
    "volume": "5,000",
    "priceBand": "$20–25/t",
    "priceLow": 20.0,
    "description": "Located in Pueblo Nuevo, Durango, Mexico, in Ejido Los Bancos. The project area is 3,704.44 ha, with 3,024 ha designated as the activity area. An IFM project under the Mexico Forest Protocol focused on sustainable forest management and carbon sequestration within an ejido-owned temperate forest landscape. Management is based on native temperate forest species. The activity area is reported as 100% native species, and key commercial species include Pinus teocote, P. durangensis, P. engelmannii, P. leiophylla, P. ayacahuite, Quercus sideroxyla, and Q. crassifolia. The project includes sustainable timber harvesting under an authorized forest management program, using MMOBI and MDS silvicultural methods, with a 60-year technical rotation and 10-year cutting cycle. Supported by a strong management and monitoring framework that includes forest inventory, CALCBOSK-based carbon accounting, field verification, fire prevention, QA/QC, and pest and disease controls. Delivers important co-benefits, including community-based forest stewardship, local participation and training, biodiversity protection, and long-term forest resilience."
  },
  {
    "key": "s17",
    "name": "Northern Cheyenne Forest Carbon Project",
    "registry": "American Carbon Registry (ACR745)",
    "vintage": "2022 – 2024",
    "creditType": "Removal",
    "category": "Forestry",
    "tech": "IFM Removals",
    "location": "Montana, USA",
    "country": "United States",
    "states": [
      "MT"
    ],
    "valueChainStates": [
      "MT"
    ],
    "methodology": "Improved Forest Management Methodology for Quantifying GHG Removals and Emission Reductions through Increased Forest Carbon Sequestration on Non-Federal U.S. Forestlands v2.0",
    "verifier": "",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "V22: 11,387 | V23: 22,618 | V24: 3,574",
    "priceBand": "$15–20/t",
    "priceLow": 16.0,
    "description": "Located on the Northern Cheyenne Indian Reservation in Rosebud and Big Horn Counties, Montana. The project area covers 90,433 acres of 100% Tribal-owned land. An IFM project focused on increasing carbon sequestration by limiting timber harvesting relative to baseline, while also improving resilience to drought and fire and maintaining forest health and other Tribal forest values. Management is based on 100% native forest ecosystems, primarily ponderosa pine forest mixed with aspen stands and riparian woodlands. Non-native species will not be introduced. The project includes sustainable timber harvesting, but at a reduced level versus baseline. Harvests and thinning are designed by the Northern Cheyenne Tribal Forestry Department and the BIA Supported by a strong management and monitoring framework, including forest inventory every 5 years or less, permanent plots, QA/QC procedures, remote-sensing verification of project area Delivers important co-benefits, including income and employment for the Tribe, improved forest health, greater fire and drought resilience, protection of wildlife habitat, and support for traditional, cultural, recreational, and aesthetic forest values. Aligned with SDGs 3, 6, 13, 15"
  },
  {
    "key": "s25",
    "name": "SPP Lost Trail IFM",
    "registry": "American Carbon Registry (ACR 1029)",
    "vintage": "2023 - 2024",
    "creditType": "Mixed",
    "category": "Forestry",
    "tech": "IFM",
    "location": "Montana, US",
    "country": "United States",
    "states": [
      "MT"
    ],
    "valueChainStates": [
      "MT"
    ],
    "methodology": "",
    "verifier": "TÜV SÜD America, Inc.",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "2023: Removals: 25,110 | Avoidance: 9,083 2024: Removals: 9,573 | Avoidance: 7,030",
    "priceBand": "$10–25/t",
    "priceLow": 14.0,
    "description": "Located on approximately 37,201 acres adjacent to the Lost Trail National Wildlife Refuge in western Montana, about 28 miles west of Kalispell, on mixed conifer timberland formerly within the Plum Creek/Weyerhaeuser ownership footprint. Greenhouse gas (GHG) reductions and removal enhancements are achieved through the deferral of timber harvest that could and would otherwise occur under the baseline scenario, allowing carbon stocks to increase above baseline levels. Carbon stocks are monitored through a combination of fixed-plot and variable-plot field sampling, with growth-and-yield modeling used to update estimates between measurement campaigns. Monitoring, reporting, and verification (MRV) occurs at least every five years. Co-benefits include biodiversity conservation, sustainable management of living natural resources, pollution prevention, water-related ecosystems, climate action, sustainable forest management, and terrestrial ecosystem protection The project contributes to the following UN SDGs SDG 6.6: Water-related ecosystems SDG 3.9: Pollution-related health impacts SDG 13.1 and 13.2: Climate action and resilience SDG 15.1, 15.2, and 15.5: Terrestrial ecosystems, sustainable forest management, and biodiversity"
  },
  {
    "key": "s9",
    "name": "Foam Blowing Agent Project 001-2023",
    "registry": "American Carbon Registry (ACR 974)",
    "vintage": "2023",
    "creditType": "Avoidance",
    "category": "Industrial gases",
    "tech": "HFC Replacement",
    "location": "Missouri, USA",
    "country": "United States",
    "states": [
      "MO"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "TÜV SÜD America, Inc.",
    "quality": [],
    "volume": "50kt+",
    "priceBand": "$0–5/t",
    "priceLow": 2.15,
    "description": "Located at a Kingspan Insulation LLC manufacturing facility in Rockford, Minnesota, where extruded polystyrene boardstock foam is produced. Greenhouse gas (GHG) reductions are achieved by replacing HFC-134a, a high-global warming potential blowing agent, with Ecomate, a near-zero global warming potential and zero-ozone depletion potential blowing agent. Blowing agent use is monitored through flow meter data recorded during production runs, purchase/usage checks, and equipment/service records to support mass-balance-based emission reduction calculations. Co-benefits include reduced GHG emissions from foam manufacturing locally, across North America through product use, and globally through avoided atmospheric emissions. The project reports no foreseeable negative community or environmental impacts. The project contributes to the following UN SDGs: SDG 9.4 sustainable industrial processes SDG 12.6 sustainable business practices SDG 13.2 climate action SDG 6.3 water quality/pollution reduction."
  },
  {
    "key": "s7",
    "name": "Foam Blowing Agent Project 002H",
    "registry": "American Carbon Registry (ACR 832, 764, 622, 556)",
    "vintage": "2019 - 2022",
    "creditType": "Avoidance",
    "category": "Industrial gases",
    "tech": "HFC Replacement",
    "location": "Virginia, USA",
    "country": "United States",
    "states": [
      "VA"
    ],
    "valueChainStates": [
      "VA"
    ],
    "methodology": "",
    "verifier": "First Environment, Inc.",
    "quality": [],
    "volume": "50,000",
    "priceBand": "$0–5/t",
    "priceLow": 1.75,
    "description": "Multiple foam manufacturing projects at Kingspan Insulation LLC's facility in Winchester, Virginia Greenhouse gas (GHG) reductions are achieved by transitioning the manufacturer from high-GWP baseline blowing agents, primarily HFC-134a, to methyl formate/Ecomate and/or methyl formate-HFO-1234ze blends, to eligible low-global warming potential alternatives Project activity is monitored through facility production records and blowing agent usage data, supporting mass-balance-based quantification consistent with the Transition to Advanced Formulation Blowing Agents methodology. The project contributes to the following UN SDGs: SDG 9 Industry, Innovation & Infrastructure — promotes adoption of low-GWP blowing agent technology and cleaner production practices SDG 12 Responsible Consumption and Production — supports low-waste, closed-loop manufacturing with near-zero environmental releases SDG 13 Climate Action — delivers voluntary industrial GHG reductions through near-zero GWP alternatives"
  },
  {
    "key": "s8",
    "name": "Foam Blowing Agent Project 002H",
    "registry": "American Carbon Registry (ACR 834)",
    "vintage": "2022",
    "creditType": "Avoidance",
    "category": "Industrial gases",
    "tech": "HFC Replacement",
    "location": "Minnesota, USA",
    "country": "United States",
    "states": [
      "MN"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "First Environment, Inc.",
    "quality": [],
    "volume": "25,000",
    "priceBand": "$0–5/t",
    "priceLow": 1.95,
    "description": "Aggregates 66 foam manufacturing facilities using 107 foam systems across North America Greenhouse gas (GHG) reductions are achieved by transitioning foam manufacturers from non-eligible baseline blowing agents, primarily HFC-134a or HFC-245fa, to Ecomate, an eligible low-global warming potential blowing agent. Project activity is monitored through Foam Supplies shipment and return records, tank weights, product information sheets, facility usage records, and maintenance/service records, supporting mass-balance-based quantification. Co-benefits include reduced GHG emissions near participating manufacturing facilities, across North America through foam product use, and globally through avoided atmospheric emissions. There were no foreseeable negative community or environmental impacts. The project contributes to the following UN SDGs: SDG 9.4 sustainable industrial processes SDG 12.6 sustainable consumption and production SDG 13.2 climate action, SDG 3.9 pollution-related health impacts SDG 6.3 water quality/pollution reduction."
  },
  {
    "key": "s26",
    "name": "Phlogiston Phase I",
    "registry": "Climate Action Reserve (CAR 1480)",
    "vintage": "2023-2024",
    "creditType": "Avoidance",
    "category": "Industrial gases",
    "tech": "N2O Abatement",
    "location": "Florida, US",
    "country": "United States",
    "states": [
      "FL"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "TÜV SÜD America Inc.",
    "quality": [
      "ICVCM CCP",
      "BeZero a"
    ],
    "volume": "50,000+",
    "priceBand": "$5–10/t",
    "priceLow": 5.75,
    "description": "Phlogiston Phase I is located in Florida, USA. It is an industrial nitrous oxide (N₂O) abatement project removing the N₂O produced as a byproduct of nylon manufacture. The project enhances emissions control by installing a high-efficiency NOₓ absorption column, enabling more N₂O emissions to be routed to a Thermal Reduction Unit (TRU) for destruction. This project not only abates the N₂O from nylon manufacturing but also utilizes the manufactured nylon in high-performance flexible food packaging, which helps minimize food waste. Emissions reductions are monitored using a continuous emissions monitoring system (CEMS), which tracks N₂O flow rates and concentrations at multiple points in the process. Data is recorded and managed through an automated acquisition system with built-in quality checks. Co Benefits include: improved air quality and reduced health risks associated with N₂O and NOₓ exposure; and modernized infrastructure with cleaner, more resilient technology. The Project contributes to the following UN SDGs: SDG 3: Good Health and Well-Being SDG 9: Industry, Innovation and Infrastructure SDG 12: Responsible Consumption and Production SDG 13: Climate Action"
  },
  {
    "key": "s6",
    "name": "Spray Foam Omega 2023C",
    "registry": "American Carbon Registry (ACR 977)",
    "vintage": "2023",
    "creditType": "Avoidance",
    "category": "Industrial gases",
    "tech": "HFC Replacement",
    "location": "Canada",
    "country": "Canada",
    "states": [],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "First Environment, Inc.",
    "quality": [],
    "volume": "25kt",
    "priceBand": "$0–5/t",
    "priceLow": 2.75,
    "description": "Covers one spray foam manufacturing facility — Huntsman Building Solutions (HBS) in Boisbriand, Quebec — producing two-component rigid PU spray foam distributed to customers across North America. Greenhouse gas (GHG) reductions are achieved by transitioning the manufacturer from high-GWP baseline blowing agents (HFC-245fa and HFC-365mfc) to Solstice HCFO-1233zd(E), an eligible low-global warming potential blowing agent. Project activity is monitored through customer sales and production records, MSDS/formulation data, mass-flow meter measurements at the reactor, and drum weight verification on calibrated scales, supporting mass-balance-based quantification. Co-benefits include reduced GHG emissions near the Boisbriand facility, across North America through foam product use, and globally through avoided atmospheric emissions. There were no foreseeable negative community or environmental impacts. The project contributes to the following UN SDGs: SDG 9.4 sustainable industrial processes SDG 12.6 sustainable consumption and production SDG 13.2 climate action SDG 3.9 pollution-related health impacts"
  },
  {
    "key": "s22",
    "name": "Recycling Roadways for Carbon Emission Reductions – Global Emissionairy (multiple projects)",
    "registry": "Verra (VCS 3839, VCS 4546, VCS 4547)",
    "vintage": "2021-2024",
    "creditType": "Avoidance",
    "category": "Materials & infrastructure",
    "tech": "Recycling road, transport, construction",
    "location": "US",
    "country": "United States",
    "states": [],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "SCS Global",
    "quality": [],
    "volume": "20,000",
    "priceBand": "$20–25/t",
    "priceLow": 20.0,
    "description": "This infrastructure-based carbon project is located in multiple states including California with additional project instances planned across the United States. This project reduces greenhouse gas emissions from road construction by replacing traditional Hot Mix Asphalt (HMA) with foam stabilized base (FSB) and asphalt emulsions. These materials allow for in-place recycling of existing roadways, avoiding emissions from mining, transport, and high-temperature mixing. The project cuts approximately 20,000 tonnes of CO₂ annually by promoting lower-emission, resource-efficient pavement solutions. Certification of compliance is documented through bills of lading and daily density testing reports, reviewed and confirmed during verification. These practices ensure consistency, transparency, and alignment with industry best practices, reinforcing the credibility and environmental integrity of the project. Co Benefits include: reduced use of virgin materials, lower energy consumption, minimized construction-related emissions, and improved durability and resilience of transportation infrastructure. The Project contributes to the following UN SDGs: SDG 9: Industry, Innovation, and Infrastructure. Promotes cleaner, more efficient construction practices SDG 12: Responsible Consumption and Production. Reduces waste through roadway recycling SDG 13: Climate Action. Cuts GHG emissions from asphalt production and use"
  },
  {
    "key": "s30",
    "name": "Bi-County Landfill Gas Destruction Project",
    "registry": "Climate Action Reserve (CAR 790)",
    "vintage": "2020+",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture",
    "location": "Tennessee, US",
    "country": "United States",
    "states": [
      "TN"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "SCS Global Services",
    "quality": [],
    "volume": "25,000",
    "priceBand": "$5–10/t",
    "priceLow": 6.0,
    "description": "The project captures and destroys landfill methane at the Bi-County Landfill located at 3212 Dover Rd, Woodlawn, Tennessee, using an open flare and two engine-generator sets (Caterpillar 3520 C+ and 3516 A+) for controlled combustion. The Project has high-quality continuous monitoring. It uses continuous methane analyzers, calibrated flow meters, and real-time flare temperature tracking, exceeding standard spot-check monitoring typical of older landfill projects. Emission reductions are calculated using continuously metered landfill gas flow, verified methane concentration, default destruction efficiencies of 96% (flare) and 93.6% (engines), a 10% soil methane oxidation factor, and IPCC AR5 methane GWP values, with conservative exclusions for low-temperature periods. Co-benefits include improved local air quality through the destruction of hazardous landfill air pollutants, reduced public health risks for nearby communities, and the creation of permanent skilled jobs supporting landfill gas operations."
  },
  {
    "key": "s23",
    "name": "Carbon Labs Plugging of Alberta Orphaned Wells V2",
    "registry": "American Carbon Registry (ACR 1093)",
    "vintage": "2024",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Plugging Orphan Oil and Gas Wells",
    "location": "Alberta, Canada",
    "country": "Canada",
    "states": [],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "GHD Limited",
    "quality": [],
    "volume": "40,000",
    "priceBand": "$15–25/t",
    "priceLow": 18.65,
    "description": "The project involves plugging one orphaned oil and gas well in the Municipal District of Red Deer County, Alberta, Canada to permanently prevent methane emissions from entering the atmosphere. Emissions reductions are confirmed through pre- and post-plugging methane measurements, demonstrating zero post-plugging emissions in accordance with the ACR Orphan Well Plugging Methodology. This is a very robust project, with proven quantifiable impact, community benefit and the ONLY player in the space of plugging O&G wells which takes responsibility for the well forever. They also work to ensure the well area matches the surrounding once they are done so if the well is in the middle of agricultural land, they plug it in such a way that the area can thereafter be used for agricultural purposes. The project delivers permanent methane abatement, producing immediate near-term climate benefits due to methane’s high short-term warming potential. Co benefits include land restoration, improved local air quality, reduced safety risks, and community benefits such as job creation and contribution to local causes via the generated revenue The Project contributes to the following UN SDGs: 03: Good Health and Well-Being; 09: Industry, Innovation and Infrastructure; 12: Responsible Consumption and Production; 13: Climate Action"
  },
  {
    "key": "s31",
    "name": "Clinton Landfill Gas Collection and Combustion Project",
    "registry": "Verra (VCS 318)",
    "vintage": "2023",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture",
    "location": "Illinois, US",
    "country": "United States",
    "states": [
      "IL"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "First Environment Inc.",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "25,000",
    "priceBand": "$5–10/t",
    "priceLow": 8.25,
    "description": "The project captures and combusts methane from the Clinton Landfill in Clinton, Illinois using an expanded landfill gas collection system and two 1.6-MW engine-generator units, with excess gas destroyed via backup flaring. Methane flow and destruction are continuously monitored using mass flow meters, methane analyzers, thermocouple-verified flare temperatures, and electronic data logging consolidated on a weekly and monthly basis Co-benefits include improved local air quality through the destruction of hazardous air pollutants, reduced health risks for nearby communities, and the creation of permanent local jobs to support landfill gas operations. The Project contributes to the following UN SDGs: SDG 3 – Good Health and Well-Being SDG 7 – Affordable and Clean Energy SDG 8 – Decent Work and Economic Growth"
  },
  {
    "key": "s13",
    "name": "Fulton County Mud Road Landfill Carbon Offset Project (LFG to Energy)",
    "registry": "Verra (VCS 834)",
    "vintage": "2023",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture/Combustion",
    "location": "New York, USA",
    "country": "United States",
    "states": [
      "NY"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "TÜV SÜD America Inc.",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "25kt",
    "priceBand": "$5–10/t",
    "priceLow": 7.75,
    "description": "Located at an active municipal solid waste landfill in Johnstown, New York (Fulton County). The Project consists of the expansion and improvement of the landfill gas (LFG) collection system, combined with a landfill gas-to-energy (LFGTE) plant. Collected landfill gas, which would otherwise be vented or flared, is combusted in two Caterpillar G3520 internal combustion engine-generators to produce electricity, significantly reducing methane emissions. MRV is very robust, following methodology ACM0001 under the Verified Carbon Standard (VCS). The project is in its second 10-year crediting period (2020–2030), with continuous system monitoring supporting accuracy and regulatory compliance. Co-Benefits include: Air quality improvement and odor reduction for surrounding communities through voluntary expansion of the gas collection system Renewable electricity generation that displaces fossil fuel-based power on the regional grid Climate change mitigation through destruction of methane (GWP of 28), directly reducing radiative forcing No known negative environmental or socio-economic impacts"
  },
  {
    "key": "s29",
    "name": "Greater New Bedford Landfill Utilization Project",
    "registry": "Verra (VCS 138)",
    "vintage": "2023",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture",
    "location": "Massachusetts, US",
    "country": "United States",
    "states": [
      "MA"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "GHD Limited",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "25,000",
    "priceBand": "$5–10/t",
    "priceLow": 7.75,
    "description": "The project is located at the Crapo Hill Landfill in Dartmouth, Massachusetts, owned by the Greater New Bedford Regional Refuse Management District. The project captures landfill gas (LFG) from the Crapo Hill Landfill and destroys the methane either through four Caterpillar 3516 engine-generators or a backup flare, converting methane to CO₂ and preventing atmospheric venting. The project also expanded the original 21-well District Initial System into a significantly larger network of vertical and horizontal wells, blowers, and header pipes. Gas flow, methane concentration, temperature, and pressure are continuously measured via a SCADA system (logged every minute, totalized hourly and daily). Methane content is measured using a California Analytical 602P NDIR analyzer (calibrated weekly), and flow is measured via an Oripac Model 5300 orifice plate meter (calibrated quarterly). Co-benefits: The project sells waste heat to an off-site anaerobic digestion facility, displacing fossil fuel use. Electricity generated is delivered to the regional grid via Eversource Energy. Local employment is supported through ongoing operations and maintenance of the facility."
  },
  {
    "key": "s28",
    "name": "Maple Hill Landfill",
    "registry": "Climate Action Reserve (CAR 521)",
    "vintage": "2022+",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture",
    "location": "Missouri, US",
    "country": "United States",
    "states": [
      "MO"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "AQC Environmental Brokerage Services, Inc.",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "45,000",
    "priceBand": "$5–10/t",
    "priceLow": 7.75,
    "description": "The project captures and destroys landfill gas (LFG) from the Maple Hill Landfill near Macon, Missouri, using a blower system connected to an open flare for continuous methane destruction. The landfill gas control system consists of 41 vertical extraction wells, collection piping, blowers, and a centralized flare station, with gas destruction via controlled combustion. Methane concentration is measured and monitored weekly using calibrated Elkins handheld gas analyzers, while LFG flow and flare temperature are continuously monitored via SCADA, with automated data uploads and long-term archival storage. Co-benefits include improved local air quality through the controlled destruction of landfill methane, reduced odor and public health risks for surrounding communities, and the support of skilled local jobs in landfill gas operations. The Project contributes to the following UN SDGs: SDG 3: Good Health and Well-Being SDG 6: Clean Water and Sanitation SDG 9: Industry, Innovation and Infrastructure SDG 13: Climate Action"
  },
  {
    "key": "s12",
    "name": "New River Landfill Gas Methane Destruction Project (LFG to Energy)",
    "registry": "CAR 560",
    "vintage": "2021",
    "creditType": "Avoidance",
    "category": "Methane capture",
    "tech": "Landfill Gas Capture/Combustion",
    "location": "US, Virginia",
    "country": "United States",
    "states": [
      "VA"
    ],
    "valueChainStates": [
      "VA"
    ],
    "methodology": "",
    "verifier": "SCS Global",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "20kt",
    "priceBand": "$5–10/t",
    "priceLow": 6.5,
    "description": "The project is located at the north of Dublin, Virginia USA. The Project consists of the collection of landfill gas (LFG) and its subsequent destruction by combustion in twelve electric generators and one open flare. The project captures and destroys landfill gas to generate electricity, significantly reducing methane emissions. MRV is very robust as the key system parameters are continuously monitored and regularly calibrated, following the U.S. Landfill Project Protocol. Weekly data collection and strong QA/QC practices ensure accuracy and regulatory compliance. Flow meters and other sensors are used to accurately measure data thus making estimation and MRV very robust Co Benefits include: Renewable energy generation that displaces fossil fuel-based electricity. Improved air quality through destruction of harmful landfill gases. Local economic benefits through energy infrastructure and maintenance jobs."
  },
  {
    "key": "s11",
    "name": "Advanced Refrigeration - ARS2023007",
    "registry": "American Carbon Registry (ACR 1114)",
    "vintage": "2024",
    "creditType": "Avoidance",
    "category": "Refrigeration",
    "tech": "Advanced Refrigeration Systems",
    "location": "Colorado, Pennsylvania",
    "country": "United States",
    "states": [
      "CO",
      "PA"
    ],
    "valueChainStates": [
      "CO"
    ],
    "methodology": "",
    "verifier": "TÜV SÜD America, Inc.",
    "quality": [],
    "volume": "From Colorado: 21,960",
    "priceBand": "$10–15/t",
    "priceLow": 12.0,
    "description": "Project is located at five new-construction cold storage facilities across Colorado (Windsor and Commerce City), Pennsylvania (Hazelton), Virginia (Glen Allen), and Minnesota (Luverne) Through this project, ultra-low GWP refrigerants R-744 and R-717 are installed in large commercial rack refrigeration systems in place of baseline HFC refrigerants, eliminating the substantial GHG emissions that would have occurred during first fill, operation, servicing, and end-of-life disposal across a 10-year crediting period — totaling 190,938 MT CO₂e in avoided emissions across all five sites The project monitors emissions reductions through a documentation-based system: contractor work orders, refrigerant charge and purchase records, system commissioning records, and site photographs confirming installation are cross-referenced for consistency; two site visits were conducted, and all records are maintained digitally for the duration of the crediting period Co-benefits include: Drastic reduction of PFAS \"forever chemicals\" that contaminate water supplies, improved energy efficiency relative to HFC systems through CO₂ heat reclaim strategies that also reduce natural gas emissions, and support for sustainable cold storage expansion enabling healthy food distribution The project contributes to UN SDGs 3, 6, 7, 9, 12, 13"
  },
  {
    "key": "s10",
    "name": "Advanced Refrigeration - ARS2025003",
    "registry": "American Carbon Registry (ACR 1188)",
    "vintage": "2024",
    "creditType": "Avoidance",
    "category": "Refrigeration",
    "tech": "Advanced Refrigeration Systems",
    "location": "Connecticut, Illinois, Maryland, and Ohio",
    "country": "United States",
    "states": [
      "CT",
      "IL",
      "MD",
      "OH"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "First Environment, Inc.",
    "quality": [
      "BeZero a"
    ],
    "volume": "41,074",
    "priceBand": "$10–15/t",
    "priceLow": 13.0,
    "description": "The project is located across six new-construction supermarket sites in Connecticut, Illinois, Maryland, and Ohio, operated by Heinen's Grocery, Pete's Market, Mom's Organic Market, Wegmans, and Acme Fresh Markets. GHG reductions are achieved by installing ultra-low-GWP refrigerant R-744 (CO₂, GWP of 1) in large commercial rack refrigeration systems in place of conventional high-GWP HFC refrigerants, avoiding emissions that would otherwise occur during first fill, operation, servicing, and end-of-life disposal over a 10-year crediting period. Monitoring is conducted once, after the final store opening date, through documentation review of manufacturer records, contractor charge records, and purchase and shipping invoices, which are cross-referenced with photos and maintained digitally by each facility owner for the duration of the crediting period. The project generates positive environmental impacts through reduced air pollutant emissions at and around each installation site, and by enabling facility owners to voluntarily choose a PFAS-free, near-zero-GWP refrigerant over higher-GWP alternatives. The project is aligned with SDG 9 (Industry, Innovation, and Infrastructure), SDG 12 (Responsible Consumption and Production), and SDG 13 (Climate Action)."
  },
  {
    "key": "s15",
    "name": "Boomitra Grassland Restoration in Northern Mexico",
    "registry": "Verra (VCS 2887)",
    "vintage": "2019-22",
    "creditType": "Removal",
    "category": "Soil & grassland",
    "tech": "Grassland Restoration",
    "location": "North Mexico",
    "country": "Mexico",
    "states": [],
    "valueChainStates": [],
    "methodology": "VM0042",
    "verifier": "",
    "quality": [
      "ICVCM CCP"
    ],
    "volume": "100,000",
    "priceBand": "$10–20/t",
    "priceLow": 11.0,
    "description": "Through this Project, ranchers are adopting Improved Grassland Management (IGM) practices, which include rotational grazing and a variety of water conservation measures Project activities clearly improve upon the baseline of continuous, unsustainable grazing by introducing rotational grazing and other improved grassland management practices. Continuity of land use has been confirmed through LULC analysis and over a decade of satellite imagery, showing no native ecosystems were cleared or converted. Co Benefits include: improved water availability through conservation measures, enhanced livelihoods via carbon credit payments and increased land productivity, reduced risk of land use change, and protection of vital habitats for regional biodiversity. Project developer has won “Earthshot Prize” and uses a proprietary robust satellite monitoring MRV system The Project contributes to the following UN SDGs: SDG 2: Zero Hunger SDG 6: Clean water & sanitization SDG 8: Decent work and economic growth SDG 13: Climate action SDG 15: Life on land"
  },
  {
    "key": "s16",
    "name": "Northern Great Plains Regenerative Grazing project",
    "registry": "Verra (VCS 1960)",
    "vintage": "2021 and 2022",
    "creditType": "Removal",
    "category": "Soil & grassland",
    "tech": "Sustainable Grazing Management",
    "location": "Montana, US",
    "country": "United States",
    "states": [
      "MT"
    ],
    "valueChainStates": [
      "MT"
    ],
    "methodology": "",
    "verifier": "Aster Global Environmental Solutions",
    "quality": [
      "BeZero a"
    ],
    "volume": "60,000",
    "priceBand": "$20–25/t",
    "priceLow": 21.0,
    "description": "Project is located at multiple ranches across Montana, and parts of Wyoming, Idaho, Washington, North Dakota, and South Dakota Through this Project, sustainable grazing practices, such as adaptive multi-paddock grazing, are implemented to restore degraded grasslands, improve soil health, and enhance carbon sequestration. The project collects detailed data from ranchers across multiple states and applies robust review procedures. Key inputs are systematically cross-checked through ranch records, recalculations, and GIS analysis. SNAPGRAZE model inputs are carefully validated to ensure alignment with approved methodologies and project documentation. Co Benefits include: Improved water infiltration and holding capacity, enhanced resilience of grasslands to drought and floods, creation of wildlife-friendly pasture mosaics that support native biodiversity, increased forage productivity, and job creation The Project contributes to the following UN SDGs: SDG 6: Clean water & sanitization SDG 8: Decent Work and Economic Growth SDG 9: Industry, Innovation, and Infrastructure SDG 13: Climate action SDG 15: Life on land"
  },
  {
    "key": "s24",
    "name": "Prairie Pothole Avoided Conversion of Grasslands and Shrublands",
    "registry": "American Carbon Registry (ACR 222)",
    "vintage": "2022+",
    "creditType": "Avoidance",
    "category": "Soil & grassland",
    "tech": "Avoided Conversion",
    "location": "US, North Dakota",
    "country": "United States",
    "states": [
      "ND"
    ],
    "valueChainStates": [],
    "methodology": "",
    "verifier": "SCS Global Services",
    "quality": [
      "BeZero aa"
    ],
    "volume": "10,924",
    "priceBand": "$15–30/t",
    "priceLow": 19.0,
    "description": "The project protects native grasslands and shrublands across 74 parcels in North Dakota, preventing conversion of these ecosystems to conventional crop cultivation. Emission reductions are generated by avoiding land conversion, preserving soil carbon stocks and native vegetation that would otherwise be released through tillage and crop production. Project lands are protected through permanent conservation easements with “sodbusting” restrictions, ensuring long-term preservation of grassland ecosystems. Monitoring includes annual easement compliance checks by the U.S. Fish & Wildlife Service and additional QA/QC using remote sensing during MRV events, verifying that land remains uncultivated. Co-benefits include biodiversity protection, soil conservation, improved watershed health, and long-term preservation of native prairie ecosystems. The Project contributes to the following UN SDGs: SDG 3: Good Health and Well-Being SDG 9: Industry, Innovation and Infrastructure SDG 13: Climate Action SDG 15: Land restoration and ecosystem protection"
  },
  {
    "key": "s14",
    "name": "Cedar Grove - Maple Valley OWC Composting Project",
    "registry": "Climate Action Reserve (CAR 866)",
    "vintage": "2023-2024",
    "creditType": "Avoidance",
    "category": "Waste & circularity",
    "tech": "Organic Waste Composting",
    "location": "Washington, US",
    "country": "United States",
    "states": [
      "WA"
    ],
    "valueChainStates": [
      "WA"
    ],
    "methodology": "",
    "verifier": "Agri-Waste Technology",
    "quality": [],
    "volume": "12,500",
    "priceBand": "$10–15/t",
    "priceLow": 13.5,
    "description": "The project aerobically composts food waste and food-soiled paper that would otherwise be landfilled, avoiding baseline methane generation from anaerobic decay at the Maple Valley, Washington composting facility. The facility operates using a GORE® Cover System and a negative-pressure Aerated Static Pile (ASP) system with biofiltration, with automated process control to maintain optimal aerobic composting conditions. Temperature, oxygen, waste sourcing, electricity use, and diesel consumption are continuously monitored Co-benefits include reduced landfill methane generation, improved regional waste diversion, production of marketable compost for soil health, and the support of skilled local jobs in compost facility operations. The Project contributes to the following UN SDGs: SDG 6: Clean Water and Sanitation SDG 11: Sustainable Cities and Communities SDG 12: Responsible Consumption and Production SDG 13: Climate Action"
  }
];
